sonar.projectKey=matta813_velora-dns_949dfea9-5574-4a76-a9cf-06342fe7567c
sonar.projectName=Velora DNS

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.exclusions=\
**/vendor/**,\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/*.min.js
